name: Deploy to Server

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code source
      - name: Récupérer le code source
        uses: actions/checkout@v3

      # 2. Mise en place de l'agent SSH
      - name: Mise en place de l'agent SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3. Copier les fichiers vers le serveur
      - name: Copier les fichiers
        run: |
          set -e
          rsync -avz --delete \
          -e "ssh -o StrictHostKeyChecking=no" \
          ./ \
          root@85.31.239.34:/var/www/william-cheron.pro
          ssh root@85.31.239.34 "rm -rf /var/www/william-cheron.pro/node_modules /var/www/william-cheron.pro/package-lock.json"

      # 4. Build la production
      - name: Build la production
        run: |
          set -e
          ssh root@85.31.239.34 "
          cd /var/www/william-cheron.pro;
          npm install;
          npm run build;
          echo 'Build terminé avec succès';
          "

      # 5. Test et Redémarrer le serveur avec PM2
      - name: Restart Portfolio
        run: |
          set -e
          ssh root@85.31.239.34 "
          cd /var/www/william-cheron.pro;
          echo 'Vérification du démarrage manuel...';
          npm start -- --test || echo 'Erreur lors du test manuel';
          pm2 delete portfolio 2>/dev/null || echo 'Aucun processus PM2 à supprimer';
          pm2 start npm --name 'portfolio' -- start --cwd /var/www/william-cheron.pro;
          pm2 save;
          pm2 list;
          "